WITH JOB_HISTORY_JOB_DAYS AS (
    SELECT
      JH.DEPARTMENT_ID,
      JH.EMPLOYEE_ID,
      EXTRACT(DAY FROM COALESCE(JH.END_DATE, CURRENT_TIMESTAMP) - JH.START_DATE) AS JH_TIME
    FROM JOB_HISTORY JH
),
    EMPLOYEE_JOB_DAYS AS (
      SELECT
        JH.DEPARTMENT_ID,
        JH.EMPLOYEE_ID,
        E.SALARY,
        SUM(JH.JH_TIME) AS WORKED_DAYS
      FROM JOB_HISTORY_JOB_DAYS JH
        INNER JOIN EMPLOYEES E ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID
      WHERE E.JOB_ID IS NOT NULL
      GROUP BY JH.DEPARTMENT_ID, JH.EMPLOYEE_ID, E.SALARY
  ),
    VETERANS_STATS AS (
      SELECT
        EJ.DEPARTMENT_ID,
        SUM(EJ.SALARY) AS VETERAN_SALARY_SUM
      FROM EMPLOYEE_JOB_DAYS EJ
      WHERE EJ.WORKED_DAYS >= ? * 364
      GROUP BY EJ.DEPARTMENT_ID
  ),
    DEPARTMENTS_STATS AS (
      SELECT
        D.DEPARTMENT_ID,
        COUNT(E.EMPLOYEE_ID) AS EMPLOYEE_COUNT,
        MIN(E.SALARY)        AS SALARY_MAX,
        MAX(E.SALARY)        AS SALARY_MIN
      FROM DEPARTMENTS D
        INNER JOIN EMPLOYEES E ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
      GROUP BY D.DEPARTMENT_ID
  )
SELECT
  DS.*,
  COALESCE(VT.VETERAN_SALARY_SUM, 0) AS VETERAN_SALARY_SUM,
  D.DEPARTMENT_NAME,
  C.COUNTRY_NAME,
  R.REGION_NAME
FROM DEPARTMENTS_STATS DS
  LEFT OUTER JOIN VETERANS_STATS VT ON VT.DEPARTMENT_ID = DS.DEPARTMENT_ID
  INNER JOIN DEPARTMENTS D ON D.DEPARTMENT_ID = DS.DEPARTMENT_ID
  INNER JOIN LOCATIONS L ON L.LOCATION_ID = D.LOCATION_ID
  INNER JOIN COUNTRIES C ON C.COUNTRY_ID = L.COUNTRY_ID
  INNER JOIN REGIONS R ON R.REGION_ID = C.REGION_ID
WHERE DS.EMPLOYEE_COUNT >= ?
ORDER BY DS.DEPARTMENT_ID
