WITH TRANSITIONS AS (
  SELECT E.EMPLOYEE_ID, COUNT(JH.EMPLOYEE_ID) - 1 as TRANSITIONS
  FROM EMPLOYEES E
    INNER JOIN JOB_HISTORY JH ON JH.EMPLOYEE_ID = E.EMPLOYEE_ID
  GROUP BY E.EMPLOYEE_ID
)
SELECT
  E.EMPLOYEE_ID,
  E.FIRST_NAME || ' ' || E.LAST_NAME AS FULL_NAME,
  J.JOB_TITLE,
  T.TRANSITIONS
FROM EMPLOYEES E
  INNER JOIN DEPARTMENTS D ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
  INNER JOIN LOCATIONS L ON L.LOCATION_ID = D.LOCATION_ID
  INNER JOIN COUNTRIES C ON C.COUNTRY_ID = L.COUNTRY_ID
  INNER JOIN REGIONS R ON R.REGION_ID = C.REGION_ID
  INNER JOIN TRANSITIONS T ON T.EMPLOYEE_ID = E.EMPLOYEE_ID
  INNER JOIN JOBS J ON J.JOB_ID = E.JOB_ID
WHERE
  R.REGION_NAME IN (?regions?) AND
  E.JOB_ID IS NOT NULL AND
  T.TRANSITIONS >= ?
ORDER BY
  E.EMPLOYEE_ID
